name: task_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+2w

environment:
  sdk: ">=3.3.0 <4.0.0"

scripts:
  build: dart run build_runner build --delete-conflicting-outputs
  fix: dart fix --apply
  apk: flutter build apk --release
  appbundle: flutter build appbundle --release
  clean: flutter clean && flutter pub get && dart fix --apply

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  hive_flutter: ^1.1.0
  dio: ^5.5.0+1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  connectivity_plus: ^6.0.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  flutter_localization: ^0.2.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_gen: ^5.6.0
  pretty_dio_logger: ^1.3.1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: I10n
  main_locale: en
  arb_dir: lib/core/localization/l10n
  output_dir: lib/core/localization/generated
