name: "Build Release" # The name of the workflow
on:
  push:
    branches:
      - "main"

jobs:
  build_android: # Define a job named "build"
    name: Android Build Release # Name of the job
    runs-on: ubuntu-latest # Use ubuntu-latest as the runner

    steps: # List of steps to perform for this job
      - uses: actions/checkout@v2

      # Setup Java environment
      - name: Setting Java Environment
        uses: actions/setup-java@v1
        with:
          java-version: "17.x"

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      # Cache Gradle files for faster builds
      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Setup Flutter environment
      - name: Setting Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"

      - name: Clean
        run: flutter clean

      # Install packages required for the app
      - name: Get Packages
        run: flutter pub get

      # Extract version number from pubspec.yaml
      - name: Extract version number
        id: version_number
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | cut -d ':' -f2 | xargs | cut -d '+' -f1)
          echo "FLUTTER_VERSION=$VERSION" >> $GITHUB_ENV

      # Build signed APK files
      - name: Build Signed APK
        run: flutter build apk --release

      # Rename the APK files using the extracted version number
      - name: Rename APK files
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/task_app-${{ env.FLUTTER_VERSION }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ env.FLUTTER_VERSION }}+${{ github.run_number }}"
          name: "task_app-${{ env.FLUTTER_VERSION }}+${{ github.run_number }}"
          body_path: CHANGELOGS.md
          files: |
            build/app/outputs/flutter-apk/*.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
